from django.urls import path
from . import views

urlpatterns = [
	path("index/",views.index,name="index"),
	path("index1/",views.index1,name="index1"),
	path("login/",views.login,name="login"),
	path("login1/",views.login1,name="login1"),
	path("login_2/",views.login_2,name="login_2"),
	path("login_3/",views.login_3,name="login_3"),
	path("signup/",views.signup,name="signup"),
	path("signup1/",views.signup1,name="signup1"),
	path("error/",views.error,name="error"),
	path("error1/",views.error1,name="error1"),
	path("change/",views.change,name="change"),	
	path("change1/",views.change1,name="change1"),
	path("owner/",views.owner,name="owner"),
	path("employee/",views.employee,name="employee"),
	path("calc/",views.calc,name="calc"),
	path("empman/",views.empman,name="empman"),
	path("menuadd/",views.menuadd,name="menuadd"),
	path("menuadd1/",views.menuadd1,name="menuadd1"),
	path("cust/",views.cust,name="cust"),
	path("cust1/",views.cust11,name="cust1"),
	path("fill/",views.fill,name="fill"),
	path("fill1/",views.fill1,name="fill1"),
	path("profile/",views.profile,name="profile"),
	path('payment/',views.payment,name="payment"),
	path("empdet/",views.empdet,name="empdet"),
	path("empdet1/",views.empdet1,name="empdet1"),
	path("delete/<int:Id>",views.delete,name="delete"),
	path("delete1/<int:Id>",views.delete1,name="delete1"),
	path("delete2/<int:Id>",views.delete2,name="delete2"),
	path("delete3/<int:Id>",views.delete3,name="delete3"),
	path("menudis/",views.menudis,name="menudis"),
	path('payment/',views.payment,name="payment"),
	path('netbank/',views.netbank,name="netbank"),
	path('cre_deb/',views.cre_deb,name="cre_deb"),
	path('sucess/',views.sucess,name="sucess"),
	path('payment1/',views.payment1,name="payment1"),
	path('netbank1/',views.netbank1,name="netbank1"),
	path('cre_deb1/',views.cre_deb1,name="cre_deb1"),
	path('sucess1/',views.sucess1,name="sucess1"),
	path('about/',views.about,name="about"),
	path('contact/',views.contact,name="contact"),

]
