# Generated by Django 3.2.4 on 2022-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_billing_system_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='first_name',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='username',
        ),
        migrations.AddField(
            model_name='user1',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
