# Generated by Django 3.2.4 on 2022-05-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_billing_system_app', '0002_auto_20220507_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user1',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
