# Generated by Django 3.2.4 on 2022-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_billing_system_app', '0005_rename_fnamr_menu_fname'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100, null=True)),
                ('cphone', models.CharField(max_length=100, null=True)),
                ('caddress', models.CharField(max_length=100, null=True)),
                ('ctype', models.CharField(max_length=100, null=True)),
                ('camount', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
