# Generated by Django 3.2.4 on 2022-05-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_billing_system_app', '0006_cust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust',
            old_name='caddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='cname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='cphone',
            new_name='phone',
        ),
    ]
