# Generated by Django 3.2.4 on 2022-05-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_billing_system_app', '0007_auto_20220508_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust',
            old_name='address',
            new_name='caddress',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='phone',
            new_name='cphone',
        ),
    ]
